version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - 4306:3306

  web:
    build: .
    image: lunchmap_rails_rails:1.0
    container_name: lunchmap_rails
    tty: true
    stdin_open: true
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app_name
      - bundle:/bundle
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    ports:
      - "4200:3000"
    depends_on:
      - db

volumes:
  mysql-data:
  bundle:
    driver: local
  yarn-cache:
    driver: local
