version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - .mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3316:3306"

  web:
    build: .
    command: "bash -c 'rm -f tmp/pids/server.pid && bundle && bin/rails db:create db:migrate db:seed && bundle exec rails server -b 0.0.0.0'"
    volumes:
      - .:/app_name
      - bundle:/bundle
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    tty: true
    stdin_open: true
    ports:
      - "6000:3000"

volumes:
  mysql-data:
  bundle:
    driver: local
  yarn-cache:
    driver: local
